# Generated by Django 4.2.7 on 2024-01-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
