# Generated by Django 4.2.7 on 2024-01-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_pcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcomment',
            name='article',
        ),
        migrations.AddField(
            model_name='pcomment',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pcomments', to='articles.comment'),
            preserve_default=False,
        ),
    ]
